### ISSUE TITLE
The Great Fras Siabi [Stratholme]

### ISSUE THREAD

**Issue by HeathcliffWoW** [renegadewow/bugtracker#234]
Description:
The game object (Premium Siabi Tobacco/176248) required to spawn Fras Siabi (11058) is not intractable by players or from within the GM phase

Current behavior:
Game object doesn't interact or spawn the boss

Expected behavior Please include links to your source (for ex. wowhead.com):
Clicking the object should spawn Fras (11058) whom drops the quest item

Steps to reproduce the problem:
1. Enter Stratholme
2. Get quest
3. Try to click the box

Useful links (ex; youtube.com): 
http://www.wowhead.com/quest=5214/the-great-fras-siabi

**Comment by Cillez** [comment]
Fixed.
