### ISSUE TITLE
Carrot on a Stick does not work

### ISSUE THREAD

**Issue by Malow** [renegadewow/bugtracker#237]
Description:
Carrot on a Stick does not seem to work.

Current behaviour:
It does nothing.

Expected behaviour Please include links to your source (for ex. wowhead.com):
It should increase mounted speed by 3%.

Steps to reproduce the problem:
1. Install an addon that shows you your movement speed.
2. Test it equipped/unequipped.

**Comment by Cillez** [comment]
Fixed.
